sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-114.pdf --upload --lsstdoc DMTN-114.tex --env=travis --ltd-product dmtn-114"
env:
  global:
    # LSST the Docs credentials
    - secure: "H/bp5BX1bUOvrY4PJI/X4iOT5PCw9a5yxSbF6pXR0+VWSj8pHgGoIiOhVM823nAta9DeeWDF+rYx4wP5NtEDXc0KchayBXuEa1LqZeb/lmEozoaK+Pj9R50wYJfcqA+EnAH/e19+08kCTLZNaWocqVfF1f/ZRkIgqv7rPmpOfgldC+5NE3ke+pPTyngrKpA8EXsaBysJwRf/moE4C4ZIw9kIG2UmfrjzC2e73w79A8jO8KfHi2vBCVkCgDxr5aPoBIv1UcnQ0cBqx+eWvyPA/cMbf+qLgyVKxfHFeP8h6wFkghDDKjwZYzuZQzmiLOaJ+e6j9gglItn8qBMera5MAxFay2vNXoyLPv6pbCwvlQkI0VzmI7qZbgWUTR86aL+oONuuNIuJ93mM8myp5jludEZhJcQzO2ChWMxWyHH8cODWKScoM+zL1yZS5lT4XcDBMKrg3MaQ2NK1fO+uzbg99rm9nrTwEo1GxKZ1Rz33kK+9mzIzIQGxvDA7YUtrBJBddeHCJld2bZpV8M9e19/LviJiNKUES0ho92lYqZYvlx6a2X37rtX4qK3u2KXXHOr/wXzRaU3bV2/TUxEKwVmSm1t4b5DzbS5UEZ1HrNn5/udZcuVwJJUrH+J6pOUnPHXTpdohsDJQG6Mt4KOoB+/HSm+GqNqeNESSDXQeABGgYLk="
    - secure: "VeIq8tMjPyTmlCoHKo8mF3BH1nDoEi8V84F7smHz0JZ6eoNg5J0rpsH/1SbDcDnBAR/keI6CCzV4grOzJqgxierPf64OFN20/gp/xZBhZDsEja3Yo8sphOQrzdI2EkXxzoO0WVEMRCeRAPjhrk7jnsLCwh+TfR6ekc3bnJJf0J8ka0EJZtQeH3px621DtExtOLvTozNlv9Ri5+qPPy2AugApIgAjvRlbraw+SK0xYrjyXxv26eaiahA05WfaQKiHbAShzwed8NJsdXoRTFooJLronlzo6BYip4vXg2QCxAIZaa4gxXiUGifJyWMf7g7pXzR+fC5GBZDe6zqfWmRqOnFstnGm+qI4Tf/Sqx9mqkYKfBnk3MCPayq+SsipekdOLwCBugtUSjobMJnE1dSohw6JzwfKzpmu91YhQlztMpj+KmnNwn9BqGQewiNSMRHzBEOBt4dxAGXI54IdV5XCIx57FnJ9P319joXFrfMOEu6LbYZ74ieNbmddxWSjuyYgU7r4jeYX/W3bTWUE7r0PDeqm5l2Kmy6smc8+BUNhc1NRz3uJEdkhgpAn94lHm3UxEZokw4ES8rue+Fz7NWOPdf7bP2ViWHF0hT2DxdcAE/48gtzqlxHTt+0s5/AdbPFry0NxrPWyjcMsVR+lKWL57A1oWRoqrkSp9u35eRYgcvQ="
